### ISSUE TITLE
Modifies input array

### ISSUE THREAD

**Issue by novemberborn** [jonschlinkert/arr-diff#3]
With v3:

``` js
const diff = require('arr-diff')

const input = ['foo', 'bar']
console.error(diff(input, ['foo'])) // ['bar']
console.error(input) // ['bar']?!
```

It looks like `diff()` modifies and returns the `input` array. I'd expect it to return a new array and not touch the original `input`.

**Comment by jonschlinkert** [comment]
sorry not sure how I missed this. I agree, we should be slicing the arrays. I can do this next time I edit the lib, or if someone wants to do a pr that would be great too

**Comment by jonschlinkert** [comment]
I refactored to ensure a new array is returned. As additional upside, I also removed a dep, and it's 3-6x faster now. https://github.com/jonschlinkert/arr-diff#benchmarks
